-- =============================================================================
-- rates_api_v1 / 02_usage.sql
-- Block: response.usage for GET /v1/rates. One row.
-- Flags: [TEST] params · [F7] usage default = regulator reference usage · [F8] TOU split + demand defaults (hardcoded, illustrative)
-- Contract change: shoulder_share + off_peak_share added; shoulder_share should become an API param.
-- NULL annual_kwh / shares = no default for this location → app should warn.
-- =============================================================================
-- ═══════════ SHARED HEADER: keep identical across 01–05 (edit once, paste to all) ═══════════
WITH
params AS (
    -- Generated by scripts/build-metabase-sql.mjs. Do not edit here: edit sql/source/ and rebuild.
    -- Values come from Metabase variables (all type Text, none required).
    -- Metabase removes [[ ... ]] when a variable is not supplied, so COALESCE uses the default.
    SELECT
        COALESCE([[ lower({{distributor}})::text, ]]  NULL::text)    AS distributor,
        COALESCE([[ {{postcode}}::text, ]]            NULL::text)    AS postcode,
        COALESCE([[ upper({{nmi}})::text, ]]          NULL::text)    AS nmi,
        COALESCE([[ {{usage_kwh}}::numeric, ]]        NULL::numeric) AS usage_kwh,
        COALESCE([[ {{peak_share}}::numeric, ]]       NULL::numeric) AS peak_share,
        COALESCE([[ {{shoulder_share}}::numeric, ]]   NULL::numeric) AS shoulder_share,
        COALESCE([[ {{max_demand_kw}}::numeric, ]]    NULL::numeric) AS max_demand_kw,
        COALESCE([[ {{offer_source}}::text, ]]        'all'::text)   AS offer_source,
        COALESCE([[ {{lim}}::int, ]]                  20::int)       AS lim,
        COALESCE([[ {{cursor_cost}}::numeric, ]]      NULL::numeric) AS cursor_cost,
        COALESCE([[ {{cursor_offer_id}}::bigint, ]]   NULL::bigint)  AS cursor_offer_id
),

-- [HARDCODED][F4] distributor → state. No state column on distributors.
-- Slugs must match the derived slugs from 00_schema_checks #2 or state resolves NULL.
network_state_map (network_slug, state) AS (
    VALUES
        ('evoenergy-electricity', 'ACT'),   -- slugs as derived from distributors.name in our DB
        ('ausgrid',           'NSW'),
        ('endeavour',         'NSW'),
        ('essential',         'NSW'),
        ('energex',           'QLD'),
        ('ergon',             'QLD'),
        ('sapower',           'SA'),
        ('tasnetworks',       'TAS'),
        ('citipower',         'VIC'),
        ('powercor',          'VIC'),
        ('jemena',            'VIC'),
        ('united',            'VIC'),
        ('ausnet',            'VIC')
),

-- [F7] Default usage = 10,000 kWh a year, the AER and ESC small business reference usage, for every network.

-- [HARDCODED][F8] Network load-profile defaults: TOU kWh split + max demand.
-- ILLUSTRATIVE, not derived from data. Replace with regulator usage profiles when sourced.
-- off_peak_share is derived (1 - peak - shoulder); peak + shoulder must be <= 1.
network_profile_defaults (network_slug, peak_share, shoulder_share, max_demand_kw) AS (
    VALUES ('evoenergy-electricity', 0.25::numeric, 0.45::numeric, 15::numeric)
),

-- [HARDCODED] Regulated small business standing offer tariffs for 2026-27, by network (DB slugs), GST inclusive.
--   Only networks with published UNIT PRICES are listed: the benchmark is always costed from them at the
--   requested usage (supply x 365 + usage x kWh), the same usage the plans are costed at.
--   published_annual_inc_gst / published_usage_kwh = the regulator's own headline figure, for reference only.
--   DMO (NSW, SE QLD, SA): AER DMO 8 final determination, Table 2.2 and Figure 2.4 (small business flat rate
--        tariff caps). The caps reproduce the published prices to the dollar.
--   VDO (VIC): ESC 2026-27 small business flat tariffs (<40 MWh) and final decision Table 3. AusNet's two
--        blocks are the same rate. The tariffs reproduce the published bills within $2 (rounding).
--   TAS: Aurora's regulated Tariff 23 (Business Single Rate) from 1 July 2026. No published annual figure.
--   Not listed (no unit prices): ACT (ICRC publishes an annual reference price only), Ergon (QCA). Update every July.
benchmark_ref (network_slug, name, regulator, period, supply_c_per_day_inc_gst, usage_c_per_kwh_inc_gst, published_annual_inc_gst, published_usage_kwh, source_url) AS (
    VALUES
        ('ausgrid',   'Default Market Offer (Ausgrid)',           'AER', '2026-27', 372.7476::numeric, 31.6293::numeric, 4523::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('endeavour', 'Default Market Offer (Endeavour Energy)',  'AER', '2026-27', 244.1375::numeric, 34.5198::numeric, 4343::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('essential', 'Default Market Offer (Essential Energy)',  'AER', '2026-27', 405.6542::numeric, 40.3667::numeric, 5517::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('energex',   'Default Market Offer (Energex)',           'AER', '2026-27', 261.6257::numeric, 28.9359::numeric, 3849::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('sapower',   'Default Market Offer (SA Power Networks)', 'AER', '2026-27', 185.5810::numeric, 44.8449::numeric, 5162::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('ausnet',    'Victorian Default Offer (AusNet)',         'ESC', '2026-27', 129.39::numeric,   34.23::numeric,   3896::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('citipower', 'Victorian Default Offer (CitiPower)',      'ESC', '2026-27', 152.19::numeric,   24.77::numeric,   3033::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('jemena',    'Victorian Default Offer (Jemena)',         'ESC', '2026-27', 167.09::numeric,   28.78::numeric,   3488::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('powercor',  'Victorian Default Offer (Powercor)',       'ESC', '2026-27', 169.78::numeric,   27.36::numeric,   3357::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('united',    'Victorian Default Offer (United Energy)',  'ESC', '2026-27', 154.00::numeric,   25.61::numeric,   3124::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('tasnetworks', 'Aurora Energy regulated small business tariff (Tariff 23)', 'OTTER', '2026-27', 170.00::numeric, 27.50::numeric, NULL::numeric, NULL::numeric, 'https://www.auroraenergy.com.au/business/products/business-all-pricing')
),

-- Location resolution.
--   [F1] slug derived from distributors.name (no slug column)
--   [F2] postcode via distributors.included_postcodes (reliability unknown)
--   [F3] NMI via first 4 chars vs identity_pattern elements (leading '^' stripped in case they're regex)
--   [F10] distributors.fuel_type = 'elec' value unverified
network AS (
    SELECT
        d.id    AS distributor_id,
        d.name  AS network_name,
        s.network_slug,
        m.state
    FROM public.distributors d
    CROSS JOIN params p
    CROSS JOIN LATERAL (
        SELECT trim(BOTH '-' FROM regexp_replace(lower(d.name), '[^a-z0-9]+', '-', 'g')) AS network_slug
    ) s
    LEFT JOIN network_state_map m ON m.network_slug = s.network_slug
    WHERE d.fuel_type::text = 'elec'
      AND CASE
            WHEN p.nmi IS NOT NULL THEN EXISTS (
                SELECT 1
                FROM unnest(d.identity_pattern) ip
                WHERE LEFT(ltrim(ip::text, '^'), 4) = LEFT(upper(p.nmi), 4)
            )
            WHEN p.distributor IS NOT NULL THEN
                s.network_slug = p.distributor
                AND (p.postcode IS NULL OR p.postcode = ANY (d.included_postcodes::text[]))
            WHEN p.postcode IS NOT NULL THEN
                p.postcode = ANY (d.included_postcodes::text[])
            ELSE FALSE
          END
),

-- Exactly one network, or nothing (ambiguous / out of coverage → no plans, no defaults)
single_network AS (
    SELECT * FROM network
    WHERE (SELECT COUNT(*) FROM network) = 1
),

usage_resolved AS (
    SELECT
        x.*,
        1 - x.peak_share - x.shoulder_share                   AS off_peak_share,
        (x.peak_share + x.shoulder_share) > 1                 AS invalid_shares
    FROM (
        SELECT
            COALESCE(p.usage_kwh,      10000::numeric)          AS annual_kwh,
            CASE WHEN p.usage_kwh IS NOT NULL THEN 'provided'
                 ELSE 'regulator_reference' END                AS usage_default_basis,
            COALESCE(p.peak_share,     npd.peak_share)         AS peak_share,
            COALESCE(p.shoulder_share, npd.shoulder_share)     AS shoulder_share,
            COALESCE(p.max_demand_kw,  npd.max_demand_kw)      AS max_demand_kw,
            array_remove(ARRAY[
                CASE WHEN p.usage_kwh      IS NULL THEN 'usage_kwh'      END,
                CASE WHEN p.peak_share     IS NULL THEN 'peak_share'     END,
                CASE WHEN p.shoulder_share IS NULL THEN 'shoulder_share' END,
                CASE WHEN p.max_demand_kw  IS NULL THEN 'max_demand_kw'  END
            ]::text[], NULL::text) AS assumed
        FROM params p
        LEFT JOIN single_network sn            ON TRUE
        LEFT JOIN network_profile_defaults npd ON npd.network_slug = sn.network_slug
    ) x
),

benchmark_resolved AS (
    -- [F11] The standing offer costed from its regulated tariff at the SAME usage as the plans.
    SELECT
        br.name,
        br.regulator,
        br.period,
        u.annual_kwh,
        ROUND((br.supply_c_per_day_inc_gst * 365 + br.usage_c_per_kwh_inc_gst * u.annual_kwh) / 100, 0)
            AS annual_cost_inc_gst,
        br.supply_c_per_day_inc_gst,
        br.usage_c_per_kwh_inc_gst,
        br.published_annual_inc_gst,
        br.published_usage_kwh,
        br.source_url
    FROM single_network sn
    JOIN benchmark_ref br ON br.network_slug = sn.network_slug
    CROSS JOIN usage_resolved u
)
-- ═══════════ END SHARED HEADER ═══════════
SELECT
    annual_kwh,
    peak_share,
    shoulder_share,        -- not in contract yet: add alongside peak_share
    off_peak_share,        -- not in contract yet: derived, 1 - peak - shoulder
    max_demand_kw,
    assumed,
    usage_default_basis,   -- provided | regulator_reference (10,000 kWh)
    invalid_shares AS _invalid_shares   -- TRUE → peak + shoulder > 1; app should 400
FROM usage_resolved
