-- =============================================================================
-- rates_api_v1 / 05_stats.sql
-- Block: response.stats for GET /v1/rates. One row.
-- Computed over ALL costed plans regardless of offer_source param (needed for both "lowest" figures).
-- ALL rates INC GST (contract says ex GST; see 04 header).
-- Flags: [TEST] · [F6] business filter = elec_offers.customer_type (lenient: drop known residential, flag unlinked) · [F8] TOU split hardcoded · [F12]–[F18] costing assumptions · [F14] bill_price INCLUDED · [F15] unbundled EXCLUDED
-- =============================================================================
-- ═══════════ SHARED HEADER: keep identical across 01–05 (edit once, paste to all) ═══════════
WITH
params AS (
    -- Generated by scripts/build-metabase-sql.mjs. Do not edit here: edit sql/source/ and rebuild.
    -- Values come from Metabase variables (all type Text, none required).
    -- Metabase removes [[ ... ]] when a variable is not supplied, so COALESCE uses the default.
    SELECT
        COALESCE([[ lower({{distributor}})::text, ]]  NULL::text)    AS distributor,
        COALESCE([[ {{postcode}}::text, ]]            NULL::text)    AS postcode,
        COALESCE([[ upper({{nmi}})::text, ]]          NULL::text)    AS nmi,
        COALESCE([[ {{usage_kwh}}::numeric, ]]        NULL::numeric) AS usage_kwh,
        COALESCE([[ {{peak_share}}::numeric, ]]       NULL::numeric) AS peak_share,
        COALESCE([[ {{shoulder_share}}::numeric, ]]   NULL::numeric) AS shoulder_share,
        COALESCE([[ {{max_demand_kw}}::numeric, ]]    NULL::numeric) AS max_demand_kw,
        COALESCE([[ {{offer_source}}::text, ]]        'all'::text)   AS offer_source,
        COALESCE([[ {{lim}}::int, ]]                  20::int)       AS lim,
        COALESCE([[ {{cursor_cost}}::numeric, ]]      NULL::numeric) AS cursor_cost,
        COALESCE([[ {{cursor_offer_id}}::bigint, ]]   NULL::bigint)  AS cursor_offer_id
),

-- [HARDCODED][F4] distributor → state. No state column on distributors.
-- Slugs must match the derived slugs from 00_schema_checks #2 or state resolves NULL.
network_state_map (network_slug, state) AS (
    VALUES
        ('evoenergy-electricity', 'ACT'),   -- slugs as derived from distributors.name in our DB
        ('ausgrid',           'NSW'),
        ('endeavour',         'NSW'),
        ('essential',         'NSW'),
        ('energex',           'QLD'),
        ('ergon',             'QLD'),
        ('sapower',           'SA'),
        ('tasnetworks',       'TAS'),
        ('citipower',         'VIC'),
        ('powercor',          'VIC'),
        ('jemena',            'VIC'),
        ('united',            'VIC'),
        ('ausnet',            'VIC')
),

-- [F7] Default usage = 10,000 kWh a year, the AER and ESC small business reference usage, for every network.

-- [HARDCODED][F8] Network load-profile defaults: TOU kWh split + max demand.
-- ILLUSTRATIVE, not derived from data. Replace with regulator usage profiles when sourced.
-- off_peak_share is derived (1 - peak - shoulder); peak + shoulder must be <= 1.
network_profile_defaults (network_slug, peak_share, shoulder_share, max_demand_kw) AS (
    VALUES ('evoenergy-electricity', 0.25::numeric, 0.45::numeric, 15::numeric)
),

-- [HARDCODED] Regulated small business standing offer tariffs for 2026-27, by network (DB slugs), GST inclusive.
--   Only networks with published UNIT PRICES are listed: the benchmark is always costed from them at the
--   requested usage (supply x 365 + usage x kWh), the same usage the plans are costed at.
--   published_annual_inc_gst / published_usage_kwh = the regulator's own headline figure, for reference only.
--   DMO (NSW, SE QLD, SA): AER DMO 8 final determination, Table 2.2 and Figure 2.4 (small business flat rate
--        tariff caps). The caps reproduce the published prices to the dollar.
--   VDO (VIC): ESC 2026-27 small business flat tariffs (<40 MWh) and final decision Table 3. AusNet's two
--        blocks are the same rate. The tariffs reproduce the published bills within $2 (rounding).
--   TAS: Aurora's regulated Tariff 23 (Business Single Rate) from 1 July 2026. No published annual figure.
--   Not listed (no unit prices): ACT (ICRC publishes an annual reference price only), Ergon (QCA). Update every July.
benchmark_ref (network_slug, name, regulator, period, supply_c_per_day_inc_gst, usage_c_per_kwh_inc_gst, published_annual_inc_gst, published_usage_kwh, source_url) AS (
    VALUES
        ('ausgrid',   'Default Market Offer (Ausgrid)',           'AER', '2026-27', 372.7476::numeric, 31.6293::numeric, 4523::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('endeavour', 'Default Market Offer (Endeavour Energy)',  'AER', '2026-27', 244.1375::numeric, 34.5198::numeric, 4343::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('essential', 'Default Market Offer (Essential Energy)',  'AER', '2026-27', 405.6542::numeric, 40.3667::numeric, 5517::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('energex',   'Default Market Offer (Energex)',           'AER', '2026-27', 261.6257::numeric, 28.9359::numeric, 3849::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('sapower',   'Default Market Offer (SA Power Networks)', 'AER', '2026-27', 185.5810::numeric, 44.8449::numeric, 5162::numeric, 10000::numeric, 'https://www.aer.gov.au/industry/registers/resources/reviews/default-market-offer-2026-27'),
        ('ausnet',    'Victorian Default Offer (AusNet)',         'ESC', '2026-27', 129.39::numeric,   34.23::numeric,   3896::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('citipower', 'Victorian Default Offer (CitiPower)',      'ESC', '2026-27', 152.19::numeric,   24.77::numeric,   3033::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('jemena',    'Victorian Default Offer (Jemena)',         'ESC', '2026-27', 167.09::numeric,   28.78::numeric,   3488::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('powercor',  'Victorian Default Offer (Powercor)',       'ESC', '2026-27', 169.78::numeric,   27.36::numeric,   3357::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('united',    'Victorian Default Offer (United Energy)',  'ESC', '2026-27', 154.00::numeric,   25.61::numeric,   3124::numeric, 10000::numeric, 'https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27'),
        ('tasnetworks', 'Aurora Energy regulated small business tariff (Tariff 23)', 'OTTER', '2026-27', 170.00::numeric, 27.50::numeric, NULL::numeric, NULL::numeric, 'https://www.auroraenergy.com.au/business/products/business-all-pricing')
),

-- Location resolution.
--   [F1] slug derived from distributors.name (no slug column)
--   [F2] postcode via distributors.included_postcodes (reliability unknown)
--   [F3] NMI via first 4 chars vs identity_pattern elements (leading '^' stripped in case they're regex)
--   [F10] distributors.fuel_type = 'elec' value unverified
network AS (
    SELECT
        d.id    AS distributor_id,
        d.name  AS network_name,
        s.network_slug,
        m.state
    FROM public.distributors d
    CROSS JOIN params p
    CROSS JOIN LATERAL (
        SELECT trim(BOTH '-' FROM regexp_replace(lower(d.name), '[^a-z0-9]+', '-', 'g')) AS network_slug
    ) s
    LEFT JOIN network_state_map m ON m.network_slug = s.network_slug
    WHERE d.fuel_type::text = 'elec'
      AND CASE
            WHEN p.nmi IS NOT NULL THEN EXISTS (
                SELECT 1
                FROM unnest(d.identity_pattern) ip
                WHERE LEFT(ltrim(ip::text, '^'), 4) = LEFT(upper(p.nmi), 4)
            )
            WHEN p.distributor IS NOT NULL THEN
                s.network_slug = p.distributor
                AND (p.postcode IS NULL OR p.postcode = ANY (d.included_postcodes::text[]))
            WHEN p.postcode IS NOT NULL THEN
                p.postcode = ANY (d.included_postcodes::text[])
            ELSE FALSE
          END
),

-- Exactly one network, or nothing (ambiguous / out of coverage → no plans, no defaults)
single_network AS (
    SELECT * FROM network
    WHERE (SELECT COUNT(*) FROM network) = 1
),

usage_resolved AS (
    SELECT
        x.*,
        1 - x.peak_share - x.shoulder_share                   AS off_peak_share,
        (x.peak_share + x.shoulder_share) > 1                 AS invalid_shares
    FROM (
        SELECT
            COALESCE(p.usage_kwh,      10000::numeric)          AS annual_kwh,
            CASE WHEN p.usage_kwh IS NOT NULL THEN 'provided'
                 ELSE 'regulator_reference' END                AS usage_default_basis,
            COALESCE(p.peak_share,     npd.peak_share)         AS peak_share,
            COALESCE(p.shoulder_share, npd.shoulder_share)     AS shoulder_share,
            COALESCE(p.max_demand_kw,  npd.max_demand_kw)      AS max_demand_kw,
            array_remove(ARRAY[
                CASE WHEN p.usage_kwh      IS NULL THEN 'usage_kwh'      END,
                CASE WHEN p.peak_share     IS NULL THEN 'peak_share'     END,
                CASE WHEN p.shoulder_share IS NULL THEN 'shoulder_share' END,
                CASE WHEN p.max_demand_kw  IS NULL THEN 'max_demand_kw'  END
            ]::text[], NULL::text) AS assumed
        FROM params p
        LEFT JOIN single_network sn            ON TRUE
        LEFT JOIN network_profile_defaults npd ON npd.network_slug = sn.network_slug
    ) x
),

benchmark_resolved AS (
    -- [F11] The standing offer costed from its regulated tariff at the SAME usage as the plans.
    SELECT
        br.name,
        br.regulator,
        br.period,
        u.annual_kwh,
        ROUND((br.supply_c_per_day_inc_gst * 365 + br.usage_c_per_kwh_inc_gst * u.annual_kwh) / 100, 0)
            AS annual_cost_inc_gst,
        br.supply_c_per_day_inc_gst,
        br.usage_c_per_kwh_inc_gst,
        br.published_annual_inc_gst,
        br.published_usage_kwh,
        br.source_url
    FROM single_network sn
    JOIN benchmark_ref br ON br.network_slug = sn.network_slug
    CROSS JOIN usage_resolved u
)
-- ═══════════ END SHARED HEADER ═══════════
-- ═══════════ SHARED COSTING BLOCK: keep identical in 04_plans.sql and 05_stats.sql ═══════════
,
offers AS (
    SELECT
        o.id                                AS offer_id,
        o.name                              AS plan_name,
        o.source::text                      AS raw_source,
        CASE WHEN LOWER(o.source::text) = 'bulk'          -- schema doc says lowercase; LOWER covers 'BULK' too
             THEN 'termina_buying_group' ELSE 'public' END AS offer_source,
        o.retailer_id,
        sn.network_slug,
        COALESCE(o.is_gst_included, FALSE)  AS is_gst_included,   -- NULL treated as ex-GST
        EXISTS (
            SELECT 1 FROM public.elec_offers eo
            WHERE eo.djangbit_offer_id = o.id
              AND eo.customer_type::text = 'BUSINESS'
        )                                   AS customer_type_verified,   -- false = no BUSINESS link (kept, flagged)
        o.offer_sheet
    FROM djangbit.offers_offer o
    JOIN single_network sn ON sn.distributor_id = o.distributor_id
    WHERE o.energy::text = 'elec'
      AND jsonb_typeof(o.offer_sheet -> 'price_lines') = 'array'
      -- Exclude site-restricted offers
      AND NOT EXISTS (
          SELECT 1 FROM djangbit.offers_offerwhitelistedsites w WHERE w.offer_id = o.id
      )
      -- [F15] Exclude unbundled / C&I offers (retail-only lines would undercost; network lines not handled yet)
      AND o.is_unbundled_tariff IS NOT TRUE
      -- [F6] BUSINESS FILTER: customer_type lives on public.elec_offers, bridged via djangbit_offer_id.
      --      LENIENT (active): drop only offers known to be residential. Offers with no elec_offers link or a NULL
      --      customer_type are KEPT and flagged customer_type_verified = false, because the strict version
      --      (link required) dropped every non-bulk offer, so only buying-group prices reached the API.
      --      EXISTS / NOT EXISTS (not JOIN) so multiple elec_offers rows per offer can't fan out.
      AND NOT EXISTS (
          SELECT 1 FROM public.elec_offers eo
          WHERE eo.djangbit_offer_id = o.id
            AND eo.customer_type::text = 'RESIDENTIAL'
      )
      -- STRICT alternative (swap with the block above): require a BUSINESS link
      -- AND EXISTS (
      --     SELECT 1 FROM public.elec_offers eo
      --     WHERE eo.djangbit_offer_id = o.id
      --       AND eo.customer_type::text = 'BUSINESS'
      -- )

      -- ── Toggles (OFF per current scope: all rates, no versioning) ──
      -- AND o.source::text IS DISTINCT FROM 'bill_price'             -- [F14] exclude offers derived from customer bills
      -- AND o.start_date >= CURRENT_DATE - INTERVAL '12 months'      -- crude "current" proxy
),

price_lines AS (
    SELECT
        o.offer_id,
        pl ->> 'tariff_type'  AS classification,
        pl ->> 'price_type'   AS price_type,
        pl ->> 'uom'          AS uom,
        -- First rule, first step only (stepped / multi-period rules simplified)
        COALESCE(
            (pl -> 'rule' -> 'rules' -> 0 -> 'consumption_steps' -> 0 ->> 'price')::numeric,
            (pl -> 'rule' -> 'rules' -> 0 ->> 'price')::numeric
        ) AS raw_price,
        LEAST(COALESCE(disc.pct, 0), 1) AS discount_pct,   -- capped: stacked discounts can't go below $0
        CASE WHEN o.is_gst_included THEN 1.0 ELSE 1.10 END AS gst_mult
    FROM offers o
    CROSS JOIN LATERAL jsonb_array_elements(o.offer_sheet -> 'price_lines') pl
    -- [F16] Percentage discounts applied unconditionally (no pay-on-time etc. distinction).
    --       Convention is fraction (check #6b: 119,132 of 119,136 non-zero values in 0–1, across all sources).
    --       4 outliers treated as whole percent (>= 1): three 1.0 on bill_price (→ 1%, not 100%), one 30 on online (→ 30%).
    --       These are data errors (offers 130783-5, 88334): fix at source and this CASE becomes a no-op.
    LEFT JOIN LATERAL (
        SELECT SUM(
                   CASE WHEN (d ->> 'value')::numeric >= 1
                        THEN (d ->> 'value')::numeric / 100
                        ELSE (d ->> 'value')::numeric END
               ) AS pct
        FROM jsonb_array_elements(
            CASE WHEN jsonb_typeof(pl -> 'rule' -> 'rules' -> 0 -> 'discount') = 'array'
                 THEN pl -> 'rule' -> 'rules' -> 0 -> 'discount'
                 ELSE '[]'::jsonb END
        ) d
        WHERE LOWER(d ->> 'discount_type') = 'percentage'
          AND (d ->> 'expire_date' IS NULL OR (d ->> 'expire_date')::date >= CURRENT_DATE)
    ) disc ON TRUE
),

priced AS (
    SELECT
        offer_id,
        classification,
        price_type,
        uom,
        raw_price * (1 - discount_pct) * gst_mult AS price_inc_gst,
        -- Fixed charges: Supply appears as per_unit/day and per_day/day (check #5) → both 365
        CASE
            WHEN price_type = 'per_day' OR lower(uom) IN ('day', 'days') THEN 365
            WHEN price_type = 'per_month' THEN 12
            WHEN price_type = 'per_year'  THEN 1
            WHEN price_type = 'per_bill'  THEN 4       -- [F12] assumes quarterly billing (not seen in check #5)
        END AS fixed_mult,
        -- Demand: all observed units are 'kW d' / 'kVA d' (check #5) → 365
        CASE
            WHEN price_type = 'per_day' OR uom ~* '(\s|/)(d|day)$' THEN 365
            WHEN price_type = 'per_year' THEN 1
            ELSE 12                                    -- [F13] per kW per month fallback (not seen in check #5)
        END AS demand_mult
    FROM price_lines
    WHERE raw_price IS NOT NULL
),

-- [F18] Demand: EVERY demand / capacity classification costed at max_demand_kw and summed.
--       kVA treated as kW (power factor 1). Overstates (low-demand windows usually see lower kW).
--       Per-classification AVG first (duplicates), then SUM across classifications.
demand_by_offer AS (
    SELECT offer_id, SUM(annual_per_kw) AS demand_annual_per_kw
    FROM (
        SELECT offer_id, classification, AVG(price_inc_gst * demand_mult) AS annual_per_kw
        FROM priced
        WHERE classification IN (
            'High Demand', 'Low Demand', 'Anytime Demand', 'Capacity Charge',
            'Network High Demand', 'Network Low Demand', 'Network Capacity Charge'
        )
        GROUP BY offer_id, classification
    ) x
    GROUP BY offer_id
),

-- [F17] Duplicate lines of the same classification (seasonal / multi-rule) are AVERAGED.
-- Not costed (per scope): Network* energy/supply, LRET/SREC/SRES/ESC, Solar FIT, Controlled Load, Greenpower.
offer_rates AS (
    SELECT
        p.offer_id,
        AVG(p.price_inc_gst) FILTER (WHERE p.classification = 'Retail Peak')                       AS peak,
        AVG(p.price_inc_gst) FILTER (WHERE p.classification = 'Retail Shoulder')                   AS shoulder,
        AVG(p.price_inc_gst) FILTER (WHERE p.classification = 'Retail Off Peak')                   AS off_peak,
        AVG(p.price_inc_gst) FILTER (WHERE p.classification IN ('Retail Anytime', 'General TOU'))  AS anytime,
        AVG(p.price_inc_gst * p.fixed_mult) FILTER (WHERE p.classification = 'Supply')             AS supply_annual,
        AVG(p.price_inc_gst * p.fixed_mult) FILTER (WHERE p.classification = 'Metering')           AS metering_annual,
        MAX(d.demand_annual_per_kw)                                                                AS demand_annual_per_kw,
        COUNT(*)                                                                                   AS n_lines
    FROM priced p
    LEFT JOIN demand_by_offer d ON d.offer_id = p.offer_id
    GROUP BY p.offer_id
),

costed AS (
    SELECT
        o.offer_id,
        o.plan_name,
        o.offer_source,
        o.raw_source,
        o.customer_type_verified,
        o.retailer_id,
        r.name AS retailer,
        o.network_slug,
        orr.peak, orr.shoulder, orr.off_peak, orr.anytime,
        orr.supply_annual, orr.metering_annual,
        orr.demand_annual_per_kw,
        orr.n_lines,
        u.max_demand_kw,
        -- Energy (hardcoded TOU split per network, [F8]):
        --   TOU:  kWh × (peak_share × peak + shoulder_share × shoulder + off_peak_share × off_peak)
        --         missing shoulder → costed at peak (two-rate TOU: peak window covers the day)
        --         missing off-peak → costed at shoulder, else peak
        --   Flat: single rate stored as 'Retail Peak' (44 Evoenergy offers, check #5) → all kWh at that rate
        CASE
            WHEN u.invalid_shares THEN NULL
            WHEN orr.peak IS NOT NULL AND (orr.off_peak IS NOT NULL OR orr.shoulder IS NOT NULL) THEN
                u.annual_kwh * (
                      u.peak_share     * orr.peak
                    + u.shoulder_share * COALESCE(orr.shoulder, orr.peak)
                    + u.off_peak_share * COALESCE(orr.off_peak, orr.shoulder, orr.peak)
                )
            WHEN COALESCE(orr.peak, orr.anytime) IS NOT NULL THEN
                u.annual_kwh * COALESCE(orr.peak, orr.anytime)
        END AS energy_annual            -- NULL = no costable energy rate, shares invalid, or usage unresolved
    FROM offers o
    JOIN offer_rates orr         ON orr.offer_id = o.offer_id
    LEFT JOIN public.retailers r ON r.id = o.retailer_id
    CROSS JOIN usage_resolved u
),

costed_total AS (
    SELECT
        c.*,
        c.energy_annual
          + COALESCE(c.supply_annual, 0)
          + COALESCE(c.metering_annual, 0)                         -- toggle: remove line to exclude metering
          + COALESCE(c.demand_annual_per_kw * c.max_demand_kw, 0)
            AS annual_cost_inc_gst,
        CASE
            WHEN c.demand_annual_per_kw IS NOT NULL THEN 'demand'
            WHEN c.peak IS NOT NULL AND (c.off_peak IS NOT NULL OR c.shoulder IS NOT NULL) THEN 'time_of_use'
            ELSE 'flat'
        END AS tariff_type,
        array_remove(ARRAY[
            CASE WHEN c.supply_annual IS NULL THEN 'no_supply_charge_found' END,
            CASE WHEN c.demand_annual_per_kw IS NOT NULL AND c.max_demand_kw IS NULL THEN 'demand_not_costed' END,
            CASE WHEN NOT c.customer_type_verified THEN 'customer_type_unverified' END
        ]::text[], NULL::text) AS plan_warnings
    FROM costed c
)
-- ═══════════ END SHARED COSTING BLOCK ═══════════
SELECT
    COUNT(*)                                                                  AS plans_costed,
    COUNT(*) FILTER (WHERE (SELECT offer_source FROM params) IN ('all', offer_source))
                                                                              AS plans_matching_filter,  -- = total across all pages
    COUNT(DISTINCT retailer_id)                                               AS retailers,
    COUNT(*) FILTER (WHERE offer_source = 'public')                           AS plans_public,
    COUNT(*) FILTER (WHERE offer_source = 'termina_buying_group')             AS plans_buying_group,
    COUNT(*) FILTER (WHERE NOT customer_type_verified)                        AS plans_customer_type_unverified,
    ROUND(MIN(annual_cost_inc_gst) FILTER (WHERE offer_source = 'public'), 0) AS lowest_public_inc_gst,
    ROUND(MIN(annual_cost_inc_gst) FILTER (WHERE offer_source = 'public' AND customer_type_verified), 0)
                                                                              AS lowest_public_verified_business_inc_gst,
    ROUND(MIN(annual_cost_inc_gst) FILTER (WHERE offer_source = 'termina_buying_group'), 0)
                                                                              AS lowest_buying_group_inc_gst,
    ROUND((
        MIN(annual_cost_inc_gst) FILTER (WHERE offer_source = 'termina_buying_group')
      / NULLIF(MIN(annual_cost_inc_gst) FILTER (WHERE offer_source = 'public'), 0) - 1
    ) * 100, 1)                                                               AS buying_group_vs_lowest_public_pct,
    ROUND((PERCENTILE_CONT(0.1) WITHIN GROUP (ORDER BY peak * 100))::numeric, 1) AS peak_c_per_kwh_inc_gst_p10,
    ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY peak * 100))::numeric, 1) AS peak_c_per_kwh_inc_gst_median,
    ROUND((PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY peak * 100))::numeric, 1) AS peak_c_per_kwh_inc_gst_p90,
    ROUND((PERCENTILE_CONT(0.1) WITHIN GROUP (ORDER BY supply_annual / 365 * 100))::numeric, 1) AS supply_c_per_day_inc_gst_p10,
    ROUND((PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY supply_annual / 365 * 100))::numeric, 1) AS supply_c_per_day_inc_gst_median,
    ROUND((PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY supply_annual / 365 * 100))::numeric, 1) AS supply_c_per_day_inc_gst_p90
FROM costed_total
WHERE annual_cost_inc_gst IS NOT NULL
-- Note: peak percentiles only include plans with a Retail Peak rate (flat plans excluded by NULL).
